version: '3.5'

services:
  cassandra:
    image: cassandra
    volumes:
      - ./datadc:/var/lib/cassandra
      - ./:/app

  cassandra-create-tables:
    container_name: cassandra-create-tables
    image: cassandra
    depends_on:
      - cassandra
    volumes:
      - ./src/main/resources:/resources
    restart: on-failure
    command: cqlsh cassandra -f /resources/create_tables.cqlsh

  webserver:
    image: openjdk:11-jdk-slim
    environment:
      - ORG_BUFISTOV_STORAGE_CASSANDRA_HOST=cassandra
      - ORG_BUFISTOV_LOG_LEVEL=info
      - SERVER_PORT=8080
    volumes:
      - ./:/webserver
    ports:
      - "8080:8080"
    working_dir: /webserver
    depends_on:
      - cassandra
    restart: on-failure
    command: bash -c "rm -rf .gradle/ && ./gradlew bootrun"

  frontend:
    image: node:latest
    environment:
      - BACKEND_PORT=8383
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - webserver
    working_dir: /frontend
    command: bash -c "npm i && npm start"

  query-populator:
    image: openjdk:11-jdk-slim
    environment:
      - BACKEND_HOST=webserver
      - BACKEND_PORT=8080
    volumes:
      - ./:/query-populator
    working_dir: /query-populator
    depends_on:
      - webserver
    restart: on-failure
    command: bash -c "rm -rf .gradle/ && ./gradlew --no-daemon runPopulator --args aol_2006_1M_queries.txt.gz"
